/*
 * Copyright 2026 zCube
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * SK6812RGBW addressable LED driver - I/O-agnostic core.
 *
 * Targets the SK6812RGBW chip (single-wire NRZ protocol, 800 kHz nominal,
 * 32 bits per LED, byte order G-R-B-W, MSB first per byte). The actual
 * waveform is generated by an "SPI bit-pattern" approach: every SK6812 bit
 * is encoded as one SPI byte clocked out at 6.4 MHz, giving:
 *
 *      sk6812 "0" = SPI 0xC0 (11000000) -> T0H=312ns / T0L=937ns
 *      sk6812 "1" = SPI 0xF0 (11110000) -> T1H=625ns / T1L=625ns
 *
 * which is well within the datasheet tolerance of +/- 150 ns. After the
 * pixel payload we send APP_LED_RESET_BYTES of 0x00 to hold the line low
 * for >80 us so the strip latches.
 *
 * Layered like the sensor drivers: this file owns the pixel buffer and
 * brightness/encoding logic; the actual SPI peripheral is bound through
 * sk6812_io_nxp_spi.{h,c}.
 */

#ifndef APP_SK6812_H
#define APP_SK6812_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Number of LEDs in the strip / matrix. Override from CMake if needed. */
#ifndef APP_LED_COUNT
#define APP_LED_COUNT             8u
#endif

/* Per-bit SPI encoding (do not change unless you also adjust the SPI
 * baudrate in sk6812_io_nxp_spi.h). */
#define APP_LED_SPI_BIT_ZERO      0xC0u
#define APP_LED_SPI_BIT_ONE       0xF0u

/* Trailing low-level bytes that produce the >80 us reset pulse. 64 bytes
 * at 6.4 MHz SPI = 80 us; we keep a small safety margin. */
#ifndef APP_LED_RESET_BYTES
#define APP_LED_RESET_BYTES       80u
#endif

/* SPI bytes per pixel: 32 SK6812 bits, each encoded as 1 SPI byte. */
#define APP_LED_SPI_PER_PIXEL     32u

/* Total transmit buffer size in bytes. */
#define APP_LED_TX_BUFFER_BYTES   ((APP_LED_COUNT * APP_LED_SPI_PER_PIXEL) + \
                                   APP_LED_RESET_BYTES)

/* One pixel: 0..255 per channel. */
typedef struct sk6812_color {
    uint8_t r;
    uint8_t g;
    uint8_t b;
    uint8_t w;
} sk6812_color_t;

#define SK6812_RGBW(R,G,B,W)  ((sk6812_color_t){(R),(G),(B),(W)})
#define SK6812_OFF            SK6812_RGBW(0,0,0,0)

/* One-shot bring-up of the SPI peripheral and clearing of all LEDs.
 * Safe to call from a FreeRTOS task. May be called more than once. */
int  sk6812_init(void);

/* Read-only count helper. */
uint16_t sk6812_count(void);

/* Set a single pixel in the in-memory frame. Out-of-range index returns -1.
 * No SPI traffic is generated until sk6812_refresh() is called. */
int  sk6812_set_pixel(uint16_t idx, sk6812_color_t c);

/* Convenience: fill the whole strip with one colour. */
int  sk6812_fill(sk6812_color_t c);

/* One-shot percent-based scaling helpers (ESP32 reference compatible).
 * The pixel buffer stores the *scaled* RGBW so subsequent refreshes will
 * still emit the dimmed colour - this is distinct from the global q8
 * `sk6812_set_brightness()` which is applied at encode time.
 *
 * brightness_pct is clamped to [0..100]. */
int  sk6812_fill_scaled(sk6812_color_t c, uint8_t brightness_pct);
int  sk6812_set_pixel_scaled(uint16_t idx, sk6812_color_t c,
                             uint8_t brightness_pct);

/* Zero every pixel and immediately push the frame (= turn the strip off
 * regardless of the current pattern). Equivalent to the ESP32
 * sk6812rgbw_clear(). */
int  sk6812_clear(void);

/* Global brightness scaler 0..255 applied at encode time. 255 = full
 * (datasheet) current. Useful for power budgeting; the per-pixel struct is
 * kept untouched so animations can fade in/out without losing colour. */
void sk6812_set_brightness(uint8_t scale);
uint8_t sk6812_get_brightness(void);

/* Encode the current pixel buffer to the SPI bit-pattern buffer and push
 * it out the SPI peripheral. Blocking; returns when the strip has latched. */
int  sk6812_refresh(void);

#ifdef __cplusplus
}
#endif

#endif /* APP_SK6812_H */
